[build]
pre-build = [                                  # additional commands to run prior to building the package
    "dpkg --add-architecture $CROSS_DEB_ARCH", 
    "apt-get update && apt-get --assume-yes install libasound2-dev:$CROSS_DEB_ARCH libudev-dev:$CROSS_DEB_ARCH clang nasm",
]

[build.env]
passthrough = ["CC=clang", "CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-linux-gnu-gcc", "RUSTFLAGS"]